apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: booking-service-monitor
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - bookmyevent
  selector:
    matchLabels:
      app: booking-service          
  endpoints:
    - port: 8004
      path: /metrics               
      interval: 15s
      scheme: http
