apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: search-service-monitor
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - bookmyevent
  selector:
    matchLabels:
      app: search-service
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
