// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics.sql

package events

import (
	"context"

	"github.com/google/uuid"
)

const getPlatformOverview = `-- name: GetPlatformOverview :one
SELECT
    COUNT(*) FILTER (WHERE status = 'published') as total_published_events,
    COUNT(*) FILTER (WHERE status = 'draft') as total_draft_events,
    SUM(total_capacity - available_seats) FILTER (WHERE status = 'published') as total_tickets_sold,
    SUM(total_capacity) FILTER (WHERE status = 'published') as total_capacity,
    ROUND(
        COALESCE(
            SUM(total_capacity - available_seats) FILTER (WHERE status = 'published')::decimal /
            NULLIF(SUM(total_capacity) FILTER (WHERE status = 'published'), 0) * 100,
            0
        ),
        2
    ) as overall_utilization
FROM events
`

type GetPlatformOverviewRow struct {
	TotalPublishedEvents int64  `json:"total_published_events"`
	TotalDraftEvents     int64  `json:"total_draft_events"`
	TotalTicketsSold     int64  `json:"total_tickets_sold"`
	TotalCapacity        int64  `json:"total_capacity"`
	OverallUtilization   string `json:"overall_utilization"`
}

// GetPlatformOverview
//
//	SELECT
//	    COUNT(*) FILTER (WHERE status = 'published') as total_published_events,
//	    COUNT(*) FILTER (WHERE status = 'draft') as total_draft_events,
//	    SUM(total_capacity - available_seats) FILTER (WHERE status = 'published') as total_tickets_sold,
//	    SUM(total_capacity) FILTER (WHERE status = 'published') as total_capacity,
//	    ROUND(
//	        COALESCE(
//	            SUM(total_capacity - available_seats) FILTER (WHERE status = 'published')::decimal /
//	            NULLIF(SUM(total_capacity) FILTER (WHERE status = 'published'), 0) * 100,
//	            0
//	        ),
//	        2
//	    ) as overall_utilization
//	FROM events
func (q *Queries) GetPlatformOverview(ctx context.Context) (GetPlatformOverviewRow, error) {
	row := q.db.QueryRowContext(ctx, getPlatformOverview)
	var i GetPlatformOverviewRow
	err := row.Scan(
		&i.TotalPublishedEvents,
		&i.TotalDraftEvents,
		&i.TotalTicketsSold,
		&i.TotalCapacity,
		&i.OverallUtilization,
	)
	return i, err
}

const getTopEventsByTicketsSold = `-- name: GetTopEventsByTicketsSold :many
SELECT
    event_id,
    name,
    total_capacity,
    available_seats,
    (total_capacity - available_seats) as tickets_sold,
    ROUND(((total_capacity - available_seats)::decimal / total_capacity::decimal) * 100, 2) as utilization,
    base_price,
    ROUND((total_capacity - available_seats) * base_price::decimal, 2) as revenue
FROM events
WHERE status = 'published'
ORDER BY tickets_sold DESC
LIMIT $1
`

type GetTopEventsByTicketsSoldRow struct {
	EventID        uuid.UUID `json:"event_id"`
	Name           string    `json:"name"`
	TotalCapacity  int32     `json:"total_capacity"`
	AvailableSeats int32     `json:"available_seats"`
	TicketsSold    int32     `json:"tickets_sold"`
	Utilization    string    `json:"utilization"`
	BasePrice      string    `json:"base_price"`
	Revenue        string    `json:"revenue"`
}

// GetTopEventsByTicketsSold
//
//	SELECT
//	    event_id,
//	    name,
//	    total_capacity,
//	    available_seats,
//	    (total_capacity - available_seats) as tickets_sold,
//	    ROUND(((total_capacity - available_seats)::decimal / total_capacity::decimal) * 100, 2) as utilization,
//	    base_price,
//	    ROUND((total_capacity - available_seats) * base_price::decimal, 2) as revenue
//	FROM events
//	WHERE status = 'published'
//	ORDER BY tickets_sold DESC
//	LIMIT $1
func (q *Queries) GetTopEventsByTicketsSold(ctx context.Context, limit int32) ([]GetTopEventsByTicketsSoldRow, error) {
	rows, err := q.db.QueryContext(ctx, getTopEventsByTicketsSold, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopEventsByTicketsSoldRow{}
	for rows.Next() {
		var i GetTopEventsByTicketsSoldRow
		if err := rows.Scan(
			&i.EventID,
			&i.Name,
			&i.TotalCapacity,
			&i.AvailableSeats,
			&i.TicketsSold,
			&i.Utilization,
			&i.BasePrice,
			&i.Revenue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
