// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package events

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Admin struct {
	AdminID      uuid.UUID             `json:"admin_id"`
	Email        string                `json:"email"`
	Name         string                `json:"name"`
	PhoneNumber  sql.NullString        `json:"phone_number"`
	PasswordHash string                `json:"password_hash"`
	Role         sql.NullString        `json:"role"`
	Permissions  pqtype.NullRawMessage `json:"permissions"`
	IsActive     sql.NullBool          `json:"is_active"`
	CreatedAt    sql.NullTime          `json:"created_at"`
	UpdatedAt    sql.NullTime          `json:"updated_at"`
}

type AdminRefreshToken struct {
	Token     string       `json:"token"`
	AdminID   uuid.UUID    `json:"admin_id"`
	ExpiresAt time.Time    `json:"expires_at"`
	RevokedAt sql.NullTime `json:"revoked_at"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type Event struct {
	EventID              uuid.UUID      `json:"event_id"`
	Name                 string         `json:"name"`
	Description          sql.NullString `json:"description"`
	VenueID              uuid.UUID      `json:"venue_id"`
	EventType            string         `json:"event_type"`
	StartDatetime        time.Time      `json:"start_datetime"`
	EndDatetime          time.Time      `json:"end_datetime"`
	TotalCapacity        int32          `json:"total_capacity"`
	AvailableSeats       int32          `json:"available_seats"`
	BasePrice            string         `json:"base_price"`
	MaxTicketsPerBooking sql.NullInt32  `json:"max_tickets_per_booking"`
	Status               sql.NullString `json:"status"`
	Version              int32          `json:"version"`
	CreatedBy            uuid.UUID      `json:"created_by"`
	CreatedAt            sql.NullTime   `json:"created_at"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
}

type Venue struct {
	VenueID      uuid.UUID             `json:"venue_id"`
	Name         string                `json:"name"`
	Address      string                `json:"address"`
	City         string                `json:"city"`
	State        sql.NullString        `json:"state"`
	Country      string                `json:"country"`
	PostalCode   sql.NullString        `json:"postal_code"`
	Capacity     int32                 `json:"capacity"`
	LayoutConfig pqtype.NullRawMessage `json:"layout_config"`
	CreatedBy    uuid.UUID             `json:"created_by"`
	CreatedAt    sql.NullTime          `json:"created_at"`
	UpdatedAt    sql.NullTime          `json:"updated_at"`
}
