---
# Init Container Job Network Policy
# The pod calls the services directly (not through the NGINX gateway) to initialize data
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: bookmyevent-init-network-policy
  namespace: bookmyevent
spec:
  podSelector:
    matchLabels:
      app: bookmyevent-init
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: user-service
      ports:
        - protocol: TCP
          port: 8001
    - to:
        - podSelector:
            matchLabels:
              app: event-service
      ports:
        - protocol: TCP
          port: 8002
    - to:
        - podSelector:
            matchLabels:
              app: search-service
      ports:
        - protocol: TCP
          port: 8003
    - to:
        - podSelector:
            matchLabels:
              app: booking-service
      ports:
        - protocol: TCP
          port: 8004
---
# Database Migration Job Network Policy
# The pod uses psql to connect to the postgres service in order to execute DDL SQL commands
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: db-migrations-network-policy
  namespace: bookmyevent
spec:
  podSelector:
    matchLabels:
      app: db-migrations
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: postgres
      ports:
        - protocol: TCP
          port: 5432
---
# Database Migration (RDS) Job Network Policy
# The pod uses psql to connect to the RDS database in order to execute DDL SQL commands
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: run-migrations-rds-network-policy
  namespace: bookmyevent
spec:
  podSelector:
    matchLabels:
      app: run-migrations-rds
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: ${RDS_VPC_CIDR}
      ports:
        - protocol: TCP
          port: 5432
