// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package users

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type RefreshToken struct {
	Token     string       `json:"token"`
	UserID    uuid.UUID    `json:"user_id"`
	ExpiresAt time.Time    `json:"expires_at"`
	RevokedAt sql.NullTime `json:"revoked_at"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type User struct {
	UserID       uuid.UUID      `json:"user_id"`
	Email        string         `json:"email"`
	PhoneNumber  sql.NullString `json:"phone_number"`
	Name         string         `json:"name"`
	PasswordHash string         `json:"password_hash"`
	IsActive     sql.NullBool   `json:"is_active"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}
