// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package users

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CheckUserExists(ctx context.Context, db DBTX, email string) (bool, error)
	CleanupExpiredTokens(ctx context.Context, db DBTX) error
	CreateRefreshToken(ctx context.Context, db DBTX, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, db DBTX, arg CreateUserParams) (User, error)
	DeactivateUser(ctx context.Context, db DBTX, userID uuid.UUID) error
	GetRefreshToken(ctx context.Context, db DBTX, token string) (RefreshToken, error)
	GetUserByEmail(ctx context.Context, db DBTX, email string) (User, error)
	GetUserByID(ctx context.Context, db DBTX, userID uuid.UUID) (User, error)
	RevokeAllUserTokens(ctx context.Context, db DBTX, userID uuid.UUID) error
	RevokeRefreshToken(ctx context.Context, db DBTX, token string) error
	UpdateUser(ctx context.Context, db DBTX, arg UpdateUserParams) (User, error)
	UpdateUserPassword(ctx context.Context, db DBTX, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
