// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package bookings

import (
	"database/sql"

	"github.com/google/uuid"
)

type Booking struct {
	BookingID        uuid.UUID      `json:"booking_id"`
	UserID           uuid.UUID      `json:"user_id"`
	EventID          uuid.UUID      `json:"event_id"`
	BookingReference string         `json:"booking_reference"`
	Quantity         int32          `json:"quantity"`
	TotalAmount      string         `json:"total_amount"`
	Status           string         `json:"status"`
	PaymentStatus    string         `json:"payment_status"`
	IdempotencyKey   sql.NullString `json:"idempotency_key"`
	BookedAt         sql.NullTime   `json:"booked_at"`
	ExpiresAt        sql.NullTime   `json:"expires_at"`
	ConfirmedAt      sql.NullTime   `json:"confirmed_at"`
	CancelledAt      sql.NullTime   `json:"cancelled_at"`
	CreatedAt        sql.NullTime   `json:"created_at"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
}

type BookingSeat struct {
	BookingSeatID uuid.UUID      `json:"booking_seat_id"`
	BookingID     uuid.UUID      `json:"booking_id"`
	SeatNumber    sql.NullString `json:"seat_number"`
	SeatRow       sql.NullString `json:"seat_row"`
	SeatSection   sql.NullString `json:"seat_section"`
	Status        sql.NullString `json:"status"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

type Payment struct {
	PaymentID            uuid.UUID      `json:"payment_id"`
	BookingID            uuid.UUID      `json:"booking_id"`
	UserID               uuid.UUID      `json:"user_id"`
	EventID              uuid.UUID      `json:"event_id"`
	Amount               string         `json:"amount"`
	Currency             sql.NullString `json:"currency"`
	PaymentMethod        sql.NullString `json:"payment_method"`
	PaymentGateway       sql.NullString `json:"payment_gateway"`
	GatewayTransactionID sql.NullString `json:"gateway_transaction_id"`
	Status               string         `json:"status"`
	TicketUrl            sql.NullString `json:"ticket_url"`
	InitiatedAt          sql.NullTime   `json:"initiated_at"`
	CompletedAt          sql.NullTime   `json:"completed_at"`
	FailedAt             sql.NullTime   `json:"failed_at"`
	ErrorMessage         sql.NullString `json:"error_message"`
	CreatedAt            sql.NullTime   `json:"created_at"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
}

type Waitlist struct {
	WaitlistID        uuid.UUID      `json:"waitlist_id"`
	EventID           uuid.UUID      `json:"event_id"`
	UserID            uuid.UUID      `json:"user_id"`
	QuantityRequested int32          `json:"quantity_requested"`
	Status            sql.NullString `json:"status"`
	JoinedAt          sql.NullTime   `json:"joined_at"`
	OfferedAt         sql.NullTime   `json:"offered_at"`
	ExpiresAt         sql.NullTime   `json:"expires_at"`
	ConvertedAt       sql.NullTime   `json:"converted_at"`
	CreatedAt         sql.NullTime   `json:"created_at"`
	UpdatedAt         sql.NullTime   `json:"updated_at"`
}
