// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package bookings

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	CreateBooking(ctx context.Context, db DBTX, arg CreateBookingParams) (Booking, error)
	CreateBookingSeat(ctx context.Context, db DBTX, arg CreateBookingSeatParams) (BookingSeat, error)
	CreatePayment(ctx context.Context, db DBTX, arg CreatePaymentParams) (Payment, error)
	DeleteBooking(ctx context.Context, db DBTX, bookingID uuid.UUID) error
	DeleteBookingSeats(ctx context.Context, db DBTX, bookingID uuid.UUID) error
	GetBookingByID(ctx context.Context, db DBTX, bookingID uuid.UUID) (Booking, error)
	GetBookingByIdempotencyKey(ctx context.Context, db DBTX, idempotencyKey sql.NullString) (Booking, error)
	GetBookingByReference(ctx context.Context, db DBTX, bookingReference string) (Booking, error)
	GetBookingSeat(ctx context.Context, db DBTX, bookingSeatID uuid.UUID) (BookingSeat, error)
	GetBookingSeats(ctx context.Context, db DBTX, bookingID uuid.UUID) ([]BookingSeat, error)
	GetBookingSeatsCount(ctx context.Context, db DBTX, bookingID uuid.UUID) (int64, error)
	GetBookingWithPayment(ctx context.Context, db DBTX, bookingID uuid.UUID) (GetBookingWithPaymentRow, error)
	GetBookingsForCleanup(ctx context.Context, db DBTX) ([]Booking, error)
	GetEventBookings(ctx context.Context, db DBTX, arg GetEventBookingsParams) ([]Booking, error)
	GetEventPayments(ctx context.Context, db DBTX, arg GetEventPaymentsParams) ([]Payment, error)
	GetEventWaitlist(ctx context.Context, db DBTX, arg GetEventWaitlistParams) ([]GetEventWaitlistRow, error)
	GetExpiredBookings(ctx context.Context, db DBTX, limit int32) ([]Booking, error)
	GetExpiredWaitlistOffers(ctx context.Context, db DBTX) ([]GetExpiredWaitlistOffersRow, error)
	GetNextWaitlistEntries(ctx context.Context, db DBTX, arg GetNextWaitlistEntriesParams) ([]GetNextWaitlistEntriesRow, error)
	GetOfferedWaitlistEntries(ctx context.Context, db DBTX) ([]GetOfferedWaitlistEntriesRow, error)
	GetPaymentByBookingID(ctx context.Context, db DBTX, bookingID uuid.UUID) (Payment, error)
	GetPaymentByGatewayTransactionID(ctx context.Context, db DBTX, gatewayTransactionID sql.NullString) (Payment, error)
	GetPaymentByID(ctx context.Context, db DBTX, paymentID uuid.UUID) (Payment, error)
	GetPaymentsForAnalytics(ctx context.Context, db DBTX, arg GetPaymentsForAnalyticsParams) ([]GetPaymentsForAnalyticsRow, error)
	GetPendingBookingByUserAndEvent(ctx context.Context, db DBTX, arg GetPendingBookingByUserAndEventParams) (Booking, error)
	GetPendingBookings(ctx context.Context, db DBTX, limit int32) ([]Booking, error)
	GetSeatsBySection(ctx context.Context, db DBTX, arg GetSeatsBySectionParams) ([]BookingSeat, error)
	GetUserBookings(ctx context.Context, db DBTX, arg GetUserBookingsParams) ([]Booking, error)
	GetUserBookingsCount(ctx context.Context, db DBTX, userID uuid.UUID) (int64, error)
	GetUserPaymentHistory(ctx context.Context, db DBTX, arg GetUserPaymentHistoryParams) ([]GetUserPaymentHistoryRow, error)
	GetUserPayments(ctx context.Context, db DBTX, arg GetUserPaymentsParams) ([]Payment, error)
	GetUserWaitlistEntry(ctx context.Context, db DBTX, arg GetUserWaitlistEntryParams) (GetUserWaitlistEntryRow, error)
	GetWaitlistEntry(ctx context.Context, db DBTX, waitlistID uuid.UUID) (GetWaitlistEntryRow, error)
	GetWaitlistEntryByUserAndEvent(ctx context.Context, db DBTX, arg GetWaitlistEntryByUserAndEventParams) (GetWaitlistEntryByUserAndEventRow, error)
	GetWaitlistEntryWithPosition(ctx context.Context, db DBTX, arg GetWaitlistEntryWithPositionParams) (GetWaitlistEntryWithPositionRow, error)
	GetWaitlistPosition(ctx context.Context, db DBTX, arg GetWaitlistPositionParams) (GetWaitlistPositionRow, error)
	GetWaitlistStats(ctx context.Context, db DBTX, eventID uuid.UUID) (GetWaitlistStatsRow, error)
	JoinWaitlist(ctx context.Context, db DBTX, arg JoinWaitlistParams) (JoinWaitlistRow, error)
	RemoveFromWaitlist(ctx context.Context, db DBTX, arg RemoveFromWaitlistParams) error
	SetWaitlistOffered(ctx context.Context, db DBTX, arg SetWaitlistOfferedParams) (SetWaitlistOfferedRow, error)
	SetWaitlistWaiting(ctx context.Context, db DBTX, waitlistID uuid.UUID) (SetWaitlistWaitingRow, error)
	UpdateBookingPaymentStatus(ctx context.Context, db DBTX, arg UpdateBookingPaymentStatusParams) (Booking, error)
	UpdateBookingSeatStatus(ctx context.Context, db DBTX, arg UpdateBookingSeatStatusParams) (BookingSeat, error)
	UpdateBookingStatus(ctx context.Context, db DBTX, arg UpdateBookingStatusParams) (Booking, error)
	UpdatePaymentStatus(ctx context.Context, db DBTX, arg UpdatePaymentStatusParams) (Payment, error)
	UpdatePaymentTicketURL(ctx context.Context, db DBTX, arg UpdatePaymentTicketURLParams) (Payment, error)
	UpdateWaitlistStatus(ctx context.Context, db DBTX, arg UpdateWaitlistStatusParams) (UpdateWaitlistStatusRow, error)
}

var _ Querier = (*Queries)(nil)
